import {readFileSync,writeFileSync,mkdirSync,copyFileSync,cpSync} from 'node:fs';
const content=JSON.parse(readFileSync('content/portfolio.json','utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const lines=s=>s.trim().split('\n').filter(Boolean);
const intro=lines(content.intro);
const nav=[['intro','Intro'],['about','About'],['education','Education'],['experience','Experience'],['venture','Venture'],['projects','Projects & Skills'],['contact','Next Chapter']];
const shell=(body,title='Karan Patel | AI Systems Engineer')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(intro[2])}"><meta name="theme-color" content="#3A3632"><title>${esc(title)}</title><link rel="stylesheet" href="/style.css">${body.includes('data-hero-name') ? `<script>document.documentElement.setAttribute('data-intro-pending','');window.introSkip=()=>{window.introSkipRequested=true};['wheel','touchstart','keydown','pointerdown'].forEach(t=>addEventListener(t,window.introSkip,{once:true,passive:true}));window.introFallback=setTimeout(()=>{document.documentElement.removeAttribute('data-intro-pending');document.querySelector('[data-menu-toggle]')?.removeAttribute('disabled')},6500)</script><script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js" defer></script><script src="/hero.js" defer></script>` : ''}<script src="/main.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="rail" data-intro-header><a class="wordmark" href="/#intro" aria-label="Karan Patel, intro">KP</a><button class="menu-toggle" data-menu-toggle aria-haspopup="dialog" aria-controls="menu" aria-expanded="false" hidden><span class="desktop-menu" aria-hidden="true">☰</span><span class="mobile-menu">Menu</span></button><noscript><a href="/#chapters">Chapters</a></noscript><span class="rail-caption">ENGINEER · BUILDER</span><button class="theme-toggle" data-theme-toggle aria-label="Switch to light theme" aria-pressed="false">◐</button><span class="rail-caption">WASHINGTON, D.C.</span><span data-header-scroll-progress aria-hidden="true"></span></header><dialog id="menu" aria-label="Chapter navigation"><button class="menu-close" autofocus>Close <span aria-hidden="true">×</span></button><nav aria-label="Chapters">${nav.map(([id,label],i)=>`<a href="/#${id}"><span class="label">${i.toString().padStart(2,'0')}</span>${esc(label)}<span aria-hidden="true">↗</span></a>`).join('')}</nav></dialog><main id="main" tabindex="-1">${body}</main></body></html>`;
const masked = value => `<span class="line-mask"><span data-line>${esc(value)}</span></span>`;
const hero=`<section class="chapter hero" id="intro" aria-labelledby="identity" data-horizontal-panel data-header-bg="transparent" data-header-text="var(--hero-text)" data-header-border="var(--hero-border)">
<div data-loading-base-overlay aria-hidden="true"></div>
<div data-hero-year aria-hidden="true"><div data-year-row><span data-year-start-text><span class="char">2</span><span class="char">0</span></span><span class="year-window"><span data-year-strip>${Array.from({length:14},(_,i)=>`<span class="year-strip-cell">${i+13}</span>`).join('')}</span></span></div></div>
<div data-hero-name><h1 id="identity" data-name-heading><span class="sr-only">Karan Patel</span><span data-name-row aria-hidden="true">${['KARAN','PATEL'].map(word=>`<span class="name-mask"><span data-name-line-text><span class="word" data-name-word>${word}</span></span></span>`).join('')}</span></h1></div>
<p class="hero-role" data-loading-tagline data-reveal-line>${masked(intro[1])}</p>
<p class="hero-intro" data-loading-journey-line data-reveal-line>${masked(intro[2])}</p>
<p class="hero-statement" data-reveal-line>${masked(intro[5])}</p>
<div class="hero-bottom"><p data-reveal-line>${masked('Washington, D.C.')}<span class="line-mask"><span data-line><time data-clock>Local time</time> · ET</span></span></p><p data-reveal-line>${masked('Open for collaborations')}</p><a class="explore to-link-underline" href="#about" data-reveal-line>${masked('SCROLL ↘')}</a></div></section>`;
let home=hero;

const paras=arr=>arr.map(x=>`<p>${esc(x)}</p>`).join('');
const chapterHead=(n,label)=>`<div class="chapter-head"><p>Chapter ${n}</p><p class="label">${label}</p></div>`;
const imageDimensions={karan:[960,960],gwu:[736,1308],nmims:[959,692],twods:[960,1358]};
const photo=(name,alt,cls='')=>`<picture class="photo ${cls}" data-reveal><source type="image/webp" srcset="/assets/${name}-480.webp 480w, /assets/${name}-960.webp ${imageDimensions[name][0]}w" sizes="(max-width:767px) calc(100vw - 40px), (max-width:1023px) calc(100vw - 64px), 44vw"><img src="/assets/${name}-960.webp" width="${imageDimensions[name][0]}" height="${imageDimensions[name][1]}" alt="${esc(name==='twods'?'Twods Capital red and black promotional artwork':alt)}" loading="lazy" decoding="async"></picture>`;
const about=lines(content.chapters[0].copy);
home+=`<section id="about" class="chapter about" aria-labelledby="about-title">${chapterHead('I','About me')}<div class="two-col about-grid"><figure>${photo('karan','Karan Patel','portrait')}<figcaption>${esc(about.slice(4,6).join(' · '))}</figcaption></figure><div><h2 id="about-title" class="medium-title" data-reveal>${esc(about[0])}</h2><div class="lead">${paras(about.slice(1,3))}</div></div></div><p class="keywords">${esc(about.slice(6).join(' · '))}</p></section>`;
const edu=lines(content.chapters[1].copy);
home+=`<section id="education" class="chapter education" aria-labelledby="education-title">${chapterHead('II','Education')}<h2 class="sr-only" id="education-title">Education</h2><div class="two-col"><article>${photo('gwu','George Washington University building with the GW sign','campus gwu')}<h3>${esc(edu[0])}</h3><p class="degree">${esc(edu[2])}</p><p>${esc(edu[3])}<br>${esc(edu[1])}</p><p>${esc(edu[4])}</p><p class="label">${esc(edu[5])}</p><p>${esc(edu[6])}</p></article><article id="nmims">${photo('nmims','NMIMS campus building','campus')}<h3>${esc(edu[7])}</h3><p class="degree">${esc(edu[8])}</p><p>${esc(edu[9])}</p></article></div></section>`;
const roles=content.chapters[2].copy.trim().split('\n\n').map(lines);
home+=`<section id="experience" class="chapter experience" aria-labelledby="experience-title">${chapterHead('III','Work experience')}<h2 id="experience-title" data-reveal>Engineering experience</h2><div class="role-list">${roles.map((r,i)=>`<details class="role"><summary><span class="role-date">${esc(r[3])}</span><span><span class="role-title">${esc(r[1])}</span><span class="employer">${esc(r[0])}</span></span><span class="row-arrow" aria-hidden="true">↗</span></summary><div class="role-body"><h3>${esc(r[2])}</h3><p>${esc(r[4])}</p><ul>${r.filter(x=>x.startsWith('* ')).map(x=>`<li>${esc(x.slice(2))}</li>`).join('')}</ul><h4 class="label">Technologies</h4><p>${esc(r.at(-1))}</p></div></details>`).join('')}</div></section>`;
const venture=lines(content.chapters[3].copy);
const vIndex=x=>venture.indexOf(x);
const growth=venture.slice(vIndex('Growth')+1,vIndex('Flagship Initiative'));
const arch=venture.slice(vIndex('Architecture')+1,vIndex('Validation')).filter(x=>x!=='↓');
const architecture=items=>`<ol class="architecture">${items.map(x=>`<li>${esc(x.replace(/^→\s*/,''))}</li>`).join('')}</ol>`;
home+=`<section id="venture" class="chapter venture dark" aria-labelledby="venture-title">${chapterHead('IV','Venture')}<div class="two-col"><div><h2 id="venture-title" data-reveal>${esc(venture[0])}</h2><p class="degree">${esc(venture[1])}</p><p class="muted">${esc(venture[2])}</p><div class="venture-story lead">${paras(venture.slice(3,5))}</div>${photo('twods','Twods Capital financial research and education preview','twods')}</div><div><dl class="metrics">${growth.filter((_,i)=>i%2===0).map((x,i)=>`<div><dt>${esc(growth[i*2+1])}</dt><dd>${esc(x)}</dd></div>`).join('')}</dl><div class="initiative"><p class="label">Flagship Initiative</p><h3>QuantEra AI</h3><p class="degree">${esc(venture[vIndex('QuantEra AI')+1])}</p>${paras(venture.slice(vIndex('QuantEra AI')+2,vIndex('Investment Thesis')))}<h4 class="label">Investment Thesis</h4><p>${esc(venture[vIndex('Investment Thesis')+1])}</p><ol class="principles">${[0,1,2].map(i=>`<li><h4>${esc(venture[vIndex('Investment Thesis')+2+i*2])}</h4><p>${esc(venture[vIndex('Investment Thesis')+3+i*2])}</p></li>`).join('')}</ol></div></div></div><details class="venture-detail"><summary>Architecture & validation <span aria-hidden="true">↗</span></summary><div class="two-col"><div><h3>Architecture</h3>${architecture(arch)}</div><div><h3>Validation</h3><p>${esc(venture[vIndex('Validation')+1])}</p><h4 class="label">Technologies</h4><p>${esc(venture.at(-1))}</p></div></div></details></section>`;
const projectCopy=content.chapters[4].copy;
const projectBlocks=projectCopy.split('PROJECT ARCHIVE')[0].split(/\n\n(?=\d\d:)/).slice(1);
const slugs=['verdict','northport','quantera-ai','bnpl-marketplace'];
const projects=projectBlocks.map((block,i)=>{const l=lines(block);const groups={};let current;for(const line of l.slice(2)){if(['Problem','Solution','Core Architecture','Architecture','Results','Result','Scale','Performance','Technologies'].includes(line)){current=line;groups[current]=[];}else if(line.startsWith('Live:')){groups.live=line.slice(6);}else if(current)groups[current].push(line);}return{name:l[0].slice(4),subtitle:l[1],slug:slugs[i],groups};});
const archive=projectCopy.split('PROJECT ARCHIVE\n')[1].split('\nSKILLS')[0].trim().split('\n\n').map(lines);
const skills=projectCopy.split('\nSKILLS\n')[1].trim().split('\n\n').map(lines);
home+=`<section id="projects" class="chapter projects" aria-labelledby="projects-title">${chapterHead('V','Projects & Skills')}<h2 id="projects-title" data-reveal>Featured Projects</h2><div class="project-list">${projects.map((p,i)=>`<a id="project-${p.slug}" class="project-row" href="/projects/${p.slug}/"><span class="project-number">${String(i+1).padStart(2,'0')}</span><span><h3>${esc(p.name)}</h3><span>${esc(p.subtitle)}</span></span><span class="row-arrow" aria-hidden="true">→</span></a>`).join('')}</div><div class="archive"><h3>Project Archive</h3>${archive.map(a=>`<article><h4>${esc(a[0])}</h4><div><p>${esc(a[1])}</p><p class="label">${esc(a[2])}</p></div></article>`).join('')}</div><div class="skills"><h3>Skills</h3>${skills.map(s=>`<section class="skill-group"><h4>${esc(s[0])}</h4><ul>${s.slice(1).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`).join('')}</div></section>`;
const contact=lines(content.chapters[5].copy);
home+=`<section id="contact" class="chapter contact dark" aria-labelledby="contact-title">${chapterHead('VI','')}<div class="two-col contact-grid"><h2 id="contact-title" data-reveal>NEXT<br>CHAPTER</h2><div class="lead">${paras(contact.slice(1,4))}</div></div><footer><div><p class="footer-name">Karan Patel</p><p class="muted">${esc(intro[1])}</p><p class="muted">Washington, D.C. / United States</p></div><p class="footer-principle">Make the system intelligent. Make the intelligence accountable.</p></footer><nav id="chapters" class="footer-nav" aria-label="Chapter index">${nav.map(([id,label])=>`<a href="#${id}">${esc(label)}</a>`).join('')}</nav></section>`;
for(const [i,p] of projects.entries()){
 const g=p.groups;const architectureKey=g['Core Architecture']?'Core Architecture':g.Architecture?'Architecture':null;
 const resultKey=['Results','Result','Scale','Performance'].find(k=>g[k]);
 const live=g.live?`<a class="live-link" href="https://${esc(g.live)}" target="_blank" rel="noopener noreferrer">Visit live project <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a>`:'';
 const next=projects[(i+1)%projects.length];
 const body=`<article class="chapter project-detail"><a class="back-link" href="/#project-${p.slug}">← Featured Projects</a><div class="two-col detail-grid"><div><h1 data-reveal>${esc(p.name)}</h1><p class="detail-subtitle">${esc(p.subtitle)}</p><section class="detail-section"><h2 class="label">Problem</h2>${paras(g.Problem)}</section><section class="detail-section"><h2 class="label">Solution</h2>${paras(g.Solution)}</section><section class="detail-section"><h2 class="label">Technologies</h2>${paras(g.Technologies)}</section>${live}</div><div>${architectureKey?`<section class="detail-section"><h2 class="label">${architectureKey}</h2>${architecture(g[architectureKey])}</section>`:''}<section class="detail-section"><h2 class="label">${resultKey}</h2><ul class="result-list">${g[resultKey].map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section></div></div><a class="next-project" href="/projects/${next.slug}/"><span class="label">Next project</span><span>${esc(next.name)}</span><span aria-hidden="true">→</span></a></article>`;
 const pageBody=p.name.length>12?body.replace('class="chapter project-detail"','class="chapter project-detail long-title"'):body;
 mkdirSync(`dist/projects/${p.slug}`,{recursive:true});writeFileSync(`dist/projects/${p.slug}/index.html`,shell(pageBody,`${p.name} | Karan Patel`));
}

mkdirSync('dist',{recursive:true});
writeFileSync('dist/index.html',shell(home));
writeFileSync('dist/style.css',readFileSync('src/tokens.css','utf8')+'\n'+readFileSync('src/style.css','utf8'));
copyFileSync('src/main.js','dist/main.js');
copyFileSync('src/hero.js','dist/hero.js');
cpSync('src/assets','dist/assets',{recursive:true});
console.log('Built static portfolio.');
